backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: 'models'
    label: 'Models'
    fields:
      - name: 'name'
        label: 'Name'
        widget: 'string'
        required: true
