backend:
  name: git-gateway
  branch: main
media_library:
  name: cloudinary
  config:
    cloud_name: dmrjua4dg
    api_key: 481127667714968
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'home'
        label: 'Home'
        file: 'content/pages/home.md'
        fields:
          - { name: 'title', label: 'Title', widget: 'string', required: true }
          - {
              name: 'description',
              label: 'Description',
              widget: 'string',
              required: true,
            }
          - {
              name: 'previewImg',
              label: 'Social Media Image',
              widget: 'image',
              allow_multiple: false,
            }
          - name: 'header'
            label: 'Header'
            widget: 'object'
            fields:
              - {
                  name: 'title',
                  label: 'Title',
                  widget: 'string',
                  required: true,
                }
              - {
                  name: 'to',
                  label: 'To Url',
                  widget: 'string',
                  required: true,
                }
              - { name: 'body', label: 'Body', widget: 'string' }
          - name: 'footer'
            label: 'Footer'
            widget: 'object'
            fields:
              - {
                  name: 'copyright',
                  label: 'Copyright',
                  widget: 'string',
                  required: true,
                }
              - {
                  name: 'linkedinUrl',
                  label: 'LinkedIn Url',
                  widget: 'string',
                  required: true,
                }
              - {
                  name: 'githubUrl',
                  label: 'Github Url',
                  widget: 'string',
                  required: true,
                }
          - {
              name: 'notFound',
              label: 'Not Found Error',
              widget: 'string',
              required: true,
            }
      - name: 'post'
        label: 'Post'
        file: 'content/pages/post.md'
        fields:
          - { name: 'title', label: 'Title', widget: 'string', required: true }
          - name: 'header'
            label: 'Header'
            widget: 'object'
            fields:
              - {
                  name: 'title',
                  label: 'Title',
                  widget: 'string',
                  required: true,
                }
              - {
                  name: 'to',
                  label: 'To Url',
                  widget: 'string',
                  required: true,
                }
          - name: 'footer'
            label: 'Footer'
            widget: 'object'
            fields:
              - {
                  name: 'copyright',
                  label: 'Copyright',
                  widget: 'string',
                  required: true,
                }
              - {
                  name: 'linkedinUrl',
                  label: 'LinkedIn Url',
                  widget: 'string',
                  required: true,
                }
              - {
                  name: 'githubUrl',
                  label: 'Github Url',
                  widget: 'string',
                  required: true,
                }
      - name: '404'
        label: '404'
        file: 'content/pages/404.md'
        fields:
          - { name: 'title', label: 'Title', widget: 'string', required: true }
          - {
              name: 'description',
              label: 'Description',
              widget: 'string',
              required: true,
            }
          - {
              name: 'previewImg',
              label: 'Social Media Image',
              widget: 'image',
              allow_multiple: false,
            }
          - name: 'header'
            label: 'Header'
            widget: 'object'
            fields:
              - {
                  name: 'title',
                  label: 'Title',
                  widget: 'string',
                  required: true,
                }
              - {
                  name: 'to',
                  label: 'To Url',
                  widget: 'string',
                  required: true,
                }
              - { name: 'body', label: 'Body', widget: 'string' }
          - name: 'footer'
            label: 'Footer'
            widget: 'object'
            fields:
              - {
                  name: 'copyright',
                  label: 'Copyright',
                  widget: 'string',
                  required: true,
                }
              - {
                  name: 'linkedinUrl',
                  label: 'LinkedIn Url',
                  widget: 'string',
                  required: true,
                }
              - {
                  name: 'githubUrl',
                  label: 'Github Url',
                  widget: 'string',
                  required: true,
                }
          - {
              name: 'notFound',
              label: 'Not Found Error',
              widget: 'string',
              required: true,
            }
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    fields:
      - { name: 'title', label: 'Title', widget: 'string', required: true }
      - { name: 'cardBody', label: 'Card Body', widget: 'string' }
      - { name: 'date', label: 'Date', widget: 'string', required: true }
      - { name: 'location', label: 'Location', widget: 'string' }
      - { name: 'locationUrl', label: 'Location Url', widget: 'string' }
      - { name: 'distance', label: 'Distance', widget: 'string' }
      - { name: 'duration', label: 'duration', widget: 'string' }
      - {
          name: 'intensity',
          label: 'Intensity',
          widget: 'select',
          options: ['Easy', 'Moderate', 'Rigorous'],
        }
      - {
          name: 'previewImg',
          label: 'Preview Img',
          widget: 'image',
          allow_multiple: false,
        }
      - { name: 'previewImgAlt', label: 'Preview Image Alt', widget: 'string' }
      - { name: 'body', 'Blog Post Content', widget: 'markdown' }
