backend:
  name: git-gateway
  branch: main
media_library:
  name: cloudinary
  config:
    cloud_name: dmrjua4dg
    api_key: 481127667714968
publish_mode: editorial_workflow
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'home'
        label: 'Home'
        file: 'content/home.md'
        fields:
          - { name: 'title', label: 'Title', widget: 'string', required: true }
          - {
              name: 'description',
              label: 'Description',
              widget: 'string',
              required: true,
            }
          - {
              name: 'previewImg',
              label: 'Social Media Image',
              widget: 'image',
              allow_multiple: false,
            }
          - name: 'hero'
            label: 'Hero'
            widget: 'object'
            required: true
            fields:
              - {
                  name: 'title',
                  label: 'Title',
                  widget: 'string',
                  required: true,
                }
              - {
                  name: 'body',
                  label: 'Body',
                  widget: 'string',
                  required: true,
                }
              - {
                  name: 'activities',
                  label: 'Activities',
                  widget: 'list',
                  required: true,
                  allow_add: true,
                }
              - name: 'cta'
                label: 'CTA'
                widget: 'object'
                required: true
                fields:
                  - {
                      name: 'label',
                      label: 'label',
                      widget: 'string',
                      required: true,
                    }
                  - {
                      name: 'tag',
                      label: 'Tag',
                      widget: 'string',
                      default: 'button',
                    }
                  - { name: 'anchor', label: 'Anchor', widget: 'string' }
              - name: 'image'
                label: 'Image'
                widget: 'object'
                required: true
                fields:
                  - {
                      name: 'src',
                      label: 'Source',
                      widget: 'image',
                      allow_multiple: false,
                      required: true,
                    }
                  - {
                      name: 'alt',
                      label: 'Alternative Text',
                      widget: 'string',
                      required: true,
                    }
          - name: 'about'
            label: 'About'
            widget: 'object'
            required: true
            fields:
              - {
                  name: 'title',
                  label: 'Title',
                  widget: 'string',
                  required: true,
                }
              - {
                  name: 'main',
                  label: 'Main',
                  widget: 'markdown',
                  required: true,
                }
              - {
                  name: 'skills',
                  label: 'Skills',
                  widget: 'list',
                  required: true,
                }
              - name: 'image'
                label: 'Image'
                widget: 'object'
                required: true
                fields:
                  - {
                      name: 'src',
                      label: 'Source',
                      widget: 'image',
                      allow_multiple: false,
                      required: true,
                    }
                  - {
                      name: 'alt',
                      label: 'Alternative Text',
                      widget: 'string',
                      required: true,
                    }
          - name: 'adventures'
            label: 'Adventures'
            widget: 'object'
            required: true
            fields:
              - {
                  name: 'title',
                  label: 'Title',
                  widget: 'string',
                  required: true,
                }
              - name: 'cta'
                label: 'CTA'
                widget: 'object'
                required: true
                fields:
                  - {
                      name: 'label',
                      label: 'label',
                      widget: 'string',
                      required: true,
                    }
                  - {
                      name: 'tag',
                      label: 'Tag',
                      widget: 'string',
                      default: 'button',
                    }
                  - { name: 'anchor', label: 'Anchor', widget: 'string' }
              - name: 'items'
                label: 'Items'
                widget: 'list'
                required: true
                fields:
                  - {
                      name: 'title',
                      label: 'Title',
                      widget: 'string',
                      required: true,
                    }
                  - {
                      name: 'description',
                      label: 'Description',
                      widget: 'string',
                      required: true,
                    }
                  - name: 'image'
                    label: 'Image'
                    widget: 'object'
                    required: true
                    fields:
                      - {
                          name: 'src',
                          label: 'Image Source',
                          widget: 'image',
                          allow_multiple: false,
                          required: true,
                        }
                      - {
                          name: 'alt',
                          label: 'Image Alt',
                          widget: 'string',
                          required: true,
                        }
      - name: 'adventures'
        label: 'Adventures'
        file: 'content/adventures.md'
        fields:
          - { name: 'title', label: 'Title', widget: 'string', required: true }
          - {
              name: 'description',
              label: 'Description',
              widget: 'string',
              required: true,
            }
          - {
              name: 'previewImg',
              label: 'Social Media Image',
              widget: 'image',
              allow_multiple: false,
            }
          - {
              name: 'notFound',
              label: 'Not Found Error',
              widget: 'string',
              required: true,
            }
      - name: 'adventure'
        label: 'Adventure'
        file: 'content/adventure.md'
        fields:
          - { name: 'title', label: 'Title', widget: 'string', required: true }
      - name: '404'
        label: '404'
        file: 'content/404.md'
        fields:
          - { name: 'title', label: 'Title', widget: 'string', required: true }
          - {
              name: 'description',
              label: 'Description',
              widget: 'string',
              required: true,
            }
          - {
              name: 'previewImg',
              label: 'Social Media Image',
              widget: 'image',
              allow_multiple: false,
            }
          - {
              name: 'notFound',
              label: 'Not Found Error',
              widget: 'string',
              required: true,
            }
  - name: 'adventures'
    label: 'Adventures'
    folder: 'content/adventures'
    create: true
    fields:
      - { name: 'title', label: 'Title', widget: 'string', required: true }
      - {
          name: 'description',
          label: 'Description',
          widget: 'string',
          required: true,
        }
      - {
          name: 'date',
          label: 'Date',
          widget: 'date',
          format: 'MM/DD/YYYY',
          required: true,
        }
      - name: 'image'
        label: 'Image'
        widget: 'object'
        required: true
        fields:
          - {
              name: 'src',
              label: 'Image Source',
              widget: 'image',
              allow_multiple: false,
              required: true,
            }
          - {
              name: 'alt',
              label: 'Image Alt',
              widget: 'string',
              required: true,
            }
      - { name: 'year', label: 'Year', widget: 'string', required: true }
      - { name: 'trail', label: 'Trail', widget: 'string', required: true }
      - { name: 'link', label: 'Link', widget: 'string', required: true }
      - { name: 'rating', label: 'Rating', widget: 'number', required: true }
      - { name: 'body', 'Blog Post Content', widget: 'markdown' }
