backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'home'
        label: 'Home'
        file: 'content/pages/home.md'
        fields:
          - { name: 'title', label: 'Title', widget: 'string', required: true }
          - {
              name: 'description',
              label: 'Description',
              widget: 'string',
              required: true,
            }
          - {
              name: 'previewImg',
              label: 'Social Media Image',
              widget: 'image',
              allow_multiple: false,
            }
  - name: 'models'
    label: 'Models'
    files:
      - name: 'header'
        label: 'Header'
        file: 'content/models/header.md'
        fields:
          - { name: 'title', label: 'Title', widget: 'string', required: true }
          - { name: 'to', label: 'To Url', widget: 'string', required: true }
          - { name: 'body', label: 'Body', widget: 'string' }
      - name: 'footer'
        label: 'Footer'
        file: 'content/models/footer.md'
        fields:
          - {
              name: 'copyright',
              label: 'Copyright',
              widget: 'string',
              required: true,
            }
          - {
              name: 'linkedinUrl',
              label: 'LinkedIn Url',
              widget: 'string',
              required: true,
            }
          - {
              name: 'githubUrl',
              label: 'Github Url',
              widget: 'string',
              required: true,
            }
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    fields:
      - { name: 'title', label: 'Title', widget: 'string', required: true }
      - { name: 'body', label: 'Body', widget: 'string', required: true }
      - { name: 'date', label: 'Date', widget: 'string', required: true }
      - {
          name: 'previewImg',
          label: 'Preview Img',
          widget: 'image',
          allow_multiple: false,
        }
      - {
          name: 'previewImgAlt',
          label: 'Preview Image Alt',
          widget: 'string',
          required: true,
        }
