backend:
  name: git-gateway
  branch: main
media_library:
  name: cloudinary
  config:
    cloud_name: dmrjua4dg
    api_key: 481127667714968
publish_mode: editorial_workflow
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'home'
        label: 'Home'
        file: 'content/pages/home.md'
        fields:
          - { name: 'title', label: 'Title', widget: 'string', required: true }
          - {
              name: 'description',
              label: 'Description',
              widget: 'string',
              required: true,
            }
          - {
              name: 'previewImg',
              label: 'Social Media Image',
              widget: 'image',
              allow_multiple: false,
            }
          - name: 'intro'
            label: 'Intro'
            widget: 'object'
            required: true
            fields:
              - {
                  name: 'title',
                  label: 'Title',
                  widget: 'string',
                  required: true,
                }
              - {
                  name: 'main',
                  label: 'Main',
                  widget: 'markdown',
                  required: true,
                }
              - name: 'cta'
                label: 'CTA'
                widget: 'object'
                required: true
                fields:
                  - {
                      name: 'label',
                      label: 'label',
                      widget: 'string',
                      required: true,
                    }
                  - {
                      name: 'tag',
                      label: 'Tag',
                      widget: 'string',
                      default: 'button',
                    }
                  - { name: 'anchor', label: 'Anchor', widget: 'string' }
          - name: 'about'
            label: 'About'
            widget: 'object'
            required: true
            fields:
              - {
                  name: 'title',
                  label: 'Title',
                  widget: 'string',
                  required: true,
                }
              - {
                  name: 'main',
                  label: 'Main',
                  widget: 'markdown',
                  required: true,
                }
              - {
                  name: 'skills',
                  label: 'Skills',
                  widget: 'list',
                  required: true,
                }
              - name: 'image'
                label: 'Image'
                widget: 'object'
                required: true
                fields:
                  - {
                      name: 'src',
                      label: 'Source',
                      widget: 'image',
                      allow_multiple: false,
                      required: true,
                    }
                  - {
                      name: 'alt',
                      label: 'Alternative Text',
                      widget: 'string',
                      required: true,
                    }
          - name: 'work'
            label: 'Work'
            widget: 'object'
            required: true
            fields:
              - {
                  name: 'title',
                  label: 'Title',
                  widget: 'string',
                  required: true,
                }
              - name: 'jobs'
                label: 'Jobs'
                widget: 'list'
                required: true
                fields:
                  - {
                      name: 'title',
                      label: 'Title',
                      widget: 'string',
                      required: true,
                    }
                  - {
                      name: 'duration',
                      label: 'Duration',
                      widget: 'string',
                      required: true,
                    }
                  - {
                      name: 'description',
                      label: 'Description',
                      widget: 'markdown',
                      required: true,
                    }
                  - {
                      name: 'isActive',
                      label: 'Is Current Job?',
                      widgeth: 'boolean',
                      required: true,
                      default: false,
                    }
          - name: 'blog'
            label: 'Blog Section'
            widget: 'object'
            required: true
            fields:
              - {
                  name: 'title',
                  label: 'Title',
                  widget: 'string',
                  required: true,
                }
              - name: 'cta'
                label: 'CTA'
                widget: 'object'
                required: true
                fields:
                  - {
                      name: 'label',
                      label: 'label',
                      widget: 'string',
                      required: true,
                    }
                  - {
                      name: 'tag',
                      label: 'Tag',
                      widget: 'string',
                      default: 'button',
                    }
                  - { name: 'anchor', label: 'Anchor', widget: 'string' }
              - name: 'posts'
                label: 'Blog Posts'
                widget: 'list'
                required: true
                fields:
                  - {
                      name: 'title',
                      label: 'Title',
                      widget: 'string',
                      required: true,
                    }
                  - {
                      name: 'description',
                      label: 'Description',
                      widget: 'string',
                      required: true,
                    }
                  - { name: 'date', label: 'Date', widget: 'string' }
                  - {
                      name: 'type',
                      label: 'Type',
                      widget: 'string',
                      default: 'blog',
                    }
                  - name: 'image'
                    label: 'Image'
                    widget: 'object'
                    required: true
                    fields:
                      - {
                          name: 'src',
                          label: 'Image Source',
                          widget: 'image',
                          allow_multiple: false,
                          required: true,
                        }
                      - {
                          name: 'alt',
                          label: 'Image Alt',
                          widget: 'string',
                          required: true,
                        }
          - name: 'contact'
            label: 'Contact'
            widget: 'object'
            required: true
            fields:
              - {
                  name: 'title',
                  label: 'Title',
                  widget: 'string',
                  required: true,
                }
              - {
                  name: 'main',
                  label: 'Main',
                  widget: 'markdown',
                  required: true,
                }
              - name: 'cta'
                label: 'CTA'
                widget: 'object'
                required: true
                fields:
                  - {
                      name: 'label',
                      label: 'label',
                      widget: 'string',
                      required: true,
                    }
                  - {
                      name: 'tag',
                      label: 'Tag',
                      widget: 'string',
                      default: 'button',
                    }
                  - { name: 'anchor', label: 'Anchor', widget: 'string' }
      - name: 'blog'
        label: 'Blog'
        file: 'content/pages/blog.md'
        fields:
          - { name: 'title', label: 'Title', widget: 'string', required: true }
          - {
              name: 'description',
              label: 'Description',
              widget: 'string',
              required: true,
            }
          - {
              name: 'previewImg',
              label: 'Social Media Image',
              widget: 'image',
              allow_multiple: false,
            }
          - {
              name: 'notFound',
              label: 'Not Found Error',
              widget: 'string',
              required: true,
            }
      - name: 'post'
        label: 'Post'
        file: 'content/pages/post.md'
        fields:
          - { name: 'title', label: 'Title', widget: 'string', required: true }
      - name: '404'
        label: '404'
        file: 'content/pages/404.md'
        fields:
          - { name: 'title', label: 'Title', widget: 'string', required: true }
          - {
              name: 'description',
              label: 'Description',
              widget: 'string',
              required: true,
            }
          - {
              name: 'previewImg',
              label: 'Social Media Image',
              widget: 'image',
              allow_multiple: false,
            }
          - {
              name: 'notFound',
              label: 'Not Found Error',
              widget: 'string',
              required: true,
            }
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    fields:
      - { name: 'title', label: 'Title', widget: 'string', required: true }
      - {
          name: 'description',
          label: 'Description',
          widget: 'string',
          required: true,
        }
      - {
          name: 'date',
          label: 'Date',
          widget: 'date',
          format: 'MM/DD/YYYY',
          required: true,
        }
      - {
          name: 'type',
          label: 'Type',
          widget: 'string',
          default: 'blog',
          required: true,
        }
      - name: 'image'
        label: 'Image'
        widget: 'object'
        required: true
        fields:
          - {
              name: 'src',
              label: 'Image Source',
              widget: 'image',
              allow_multiple: false,
              required: true,
            }
          - {
              name: 'alt',
              label: 'Image Alt',
              widget: 'string',
              required: true,
            }
      - { name: 'body', 'Blog Post Content', widget: 'markdown' }
