backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'home'
        label: 'Home'
        file: 'content/pages/home.md'
        fields:
          - { name: 'title', label: 'Title', widget: 'string' }
          - { name: 'description', label: 'Description', widget: 'string' }
          - {
              name: 'previewImg',
              label: 'Social Media Image',
              widget: 'image',
              allow_multiple: false,
            }
